### ISSUE TITLE
Feature: User can view homepage with recipe of the day

### ISSUE THREAD

**Issue by calvin-tran1** [calvin-tran1/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Recipe of the day will be displayed on the homepage.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Every 24 hours a random recipe will be displayed on the homepage.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103145813/173407947-3059bdf6-ca19-47e7-8179-b794e912be8c.png)
![image](https://user-images.githubusercontent.com/103145813/173408007-645a9dd4-55fa-4711-a02b-a64af7768638.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] #2
- [x] Create navbar
- [x] Create banner indicating Recipe of the day!
- [x] Get API data to display a random recipe on the page every 24 hours
- [x] Create a favorite icon
- [x] Create a mobile view 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
