### ISSUE TITLE
Feature: User can edit their saved original recipes

### ISSUE THREAD

**Issue by calvin-tran1** [calvin-tran1/ajax-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Edit their recipes
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking the pencil icon from "Your Recipes" will allow the user to edit the selected recipe.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/103145813/173457376-7c625846-091f-42a1-b9a7-d5fe710c9455.png)
![image](https://user-images.githubusercontent.com/103145813/173457447-284f88e0-4bf5-45a1-9c30-fe9ce0871458.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Clicking the pencil icon will return the user to the form page
- [x] Populate selected recipe's data into the input fields
- [x] Saving edit replaces previous entry with matching ID
- [x] Create delete button
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
