### ISSUE TITLE
Feature: User can delete recipes

### ISSUE THREAD

**Issue by calvin-tran1** [calvin-tran1/ajax-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete recipes.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking the trash icon will prompt a modal to confirm if user wants to delete their recipe.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103145813/173458078-9b425199-7bda-4c0f-abd8-191bf66610c0.png)
![image](https://user-images.githubusercontent.com/103145813/173458097-112bfa3f-8ec9-4365-a20b-c8a24c71e9cd.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make trash icon interactive
- [x] Create modal confirming if user wants to delete their recipe
- [x] Create backdrop for modal
- [x] Clicking trash icon will prompt the modal
- [x] Clicking cancel will hide the modal and backdrop
- [x] Clicking confirm will delete the recipe from the "Your Recipes" list
- [x] Confirm will also redirect user to "Your Recipes" page
- [x] Ensure the favorite icons are appropriately colored/interactive where necessary
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
