### ISSUE TITLE
Feature: Search

### ISSUE THREAD

**Issue by calvin-tran1** [calvin-tran1/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/103145813/173449335-17cae34f-3c19-4282-b00c-fffb3fa6145b.png)
![image](https://user-images.githubusercontent.com/103145813/173449378-4e4108fb-061b-48a7-85a8-2353307aaada.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Make search bar functional
- [ ] Entering search returns a list of recipes that contain the keyword(s)
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
