### ISSUE TITLE
Feature: User can search recipes

### ISSUE THREAD

**Issue by calvin-tran1** [calvin-tran1/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will have a functional search bar.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking and entering text within the search bar will return a list of recipes that match the keyword(s) from the input field.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/103145813/173450106-456b092b-fe30-4c4d-91cf-9c92545931aa.png)
![image](https://user-images.githubusercontent.com/103145813/173450141-f194efab-6c52-4b5e-aee3-0d1ca1446782.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Render all recipes from API
- [x] Entering search returns list of recipes containing the keyword(s)
- [x] "RECIPE BOOK" returns user back to home page with the recipe of the day
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
