### ISSUE TITLE
Feature: User can select and view searched recipes

### ISSUE THREAD

**Issue by calvin-tran1** [calvin-tran1/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

From a list of returned searches, the user can view the selected recipe.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking the title of the recipe will navigate the user to a page with the desired recipe returning its full list of ingredients and a link to the full recipe.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/103145813/173450787-1d19101e-9cb2-4c1c-92b2-ff20aaf1e4b6.png)
![image](https://user-images.githubusercontent.com/103145813/173450843-e00b3226-1600-4ef6-a068-e955a9b93f5a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Render all recipes
- [ ] Typing keyword in search box will return a list of recipes matching it
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
