### ISSUE TITLE
Feature: User can favorite recipes

### ISSUE THREAD

**Issue by calvin-tran1** [calvin-tran1/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can favorite recipes.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the heart to favorite/unfavorite recipes and navigate to a page that returns a list of favorited recipes.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/103145813/173451492-91dff54f-5a55-40b9-a81c-b0dcac21a056.png)
![image](https://user-images.githubusercontent.com/103145813/173451526-479f5871-28db-4a37-bdd4-c8f42a929796.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make favorite button interactive
- [x] Clicking on favorite button will save recipe
- [x] Render favorite recipes
- [x] Clicking on "Your Favorites" will redirect user to a page with a list of the user's marked favorites
- [x] Clicking the favorite icon again on a marked recipe will unfavorite the recipe from the favorites list
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
