### ISSUE TITLE
Feature: User can have access to menu list in mobile view

### ISSUE THREAD

**Issue by calvin-tran1** [calvin-tran1/ajax-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can navigate to different pages of the website in mobile view
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking menu icon in mobile view will drop down a menu list allowing users to navigate to different portions of the webpage
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/103145813/173452502-ceeab1e5-b519-4d8d-9f7b-c91552e31eaf.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Make menu icon interactive in mobile view
- [ ] Create a menu list with "Your Favorites" and "Your Recipes" navigation
- [ ] Create background with a dark opacity when menu is clicked
- [ ] Clicking "Your Favorites" navigates the user to a list of favorited recipes
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
