### ISSUE TITLE
Feature: User can write their own recipes

### ISSUE THREAD

**Issue by calvin-tran1** [calvin-tran1/ajax-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to enter and save their own recipes.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on either the "+" button in mobile view, or "Write a Recipe" in desktop view will navigate user to a form page that allows the user to input data within the fields to store their very own recipes!
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103145813/173454240-90b120eb-85f3-4851-9110-fa5fd9c9f17b.png)
![image](https://user-images.githubusercontent.com/103145813/173454312-b0310585-4eb6-490d-af2e-42b72ce628b3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a placeholder for an image of the user's recipe
- [x] Create titles and input fields matching the wireframes
- [x] Write placeholder texts within the input fields
- [x] Create "CANCEL" and "SAVE" buttons
- [x] "SAVE" button pushes values to entries array
- [x] Clicking "CANCEL" will return the user to the home page
- [x] Clicking "Write a Recipe" redirects user to entry form
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
