### ISSUE TITLE
Feature: User can view their saved original recipes

### ISSUE THREAD

**Issue by calvin-tran1** [calvin-tran1/ajax-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

View their saved original recipes!
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on "Your Recipes" from the navbar/menu list(mobile) will navigate the user to a page with their saved entries.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103145813/173456169-813f2b0d-cd85-4b59-a5c4-7b4b1442bba4.png)
![image](https://user-images.githubusercontent.com/103145813/173456246-1ba1c6cb-3243-44d5-b0c1-fb02c5955396.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Render original recipes from data.js
- [x] Create a pencil icon placed to the right of the recipe title
- [x] Page view is saved upon page refresh
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
